### ISSUE TITLE
Update Contribution Guide

### ISSUE THREAD

**Issue by danielcbright** [DataDog/dpn#13]
## Description
We want to update the Contribution Guide to: 
- make it clearer that not only entire sandbox apps are welcome, also smaller bits (TF scripts, API scripts) are welcome. 
- make it clear that we want to keep number of sandbox apps in total small, so we do not have too many redundancies.

## Proposal
Updated the doc (see PR). 

## Acceptance Criteria

**Comment by chrisluekermann** [comment]
I modified the Contributions Guide but not the "Contributing Sample Apps" Guide yet as that may need to change regarding our possible Terraform strategy.

**Comment by danielcbright** [comment]
@danielcbright note to self - use this issue to track validation of the contribution guide

**Comment by danielcbright** [comment]
cancel the above, PR was already created, I will use that to review :)
