### ISSUE TITLE
Terraform as the only deployment configuration?

### ISSUE THREAD

**Issue by chrisluekermann** [DataDog/dpn#15]
While working through the existing sandbox apps, I started drawing out all the deployments we support in some apps and that we may want to support going forward: 
- Vagrant (?)
- docker-compose
- Kubernetes
- AWS
- GCP
- Azure

And when we pair up all these different deployments with the planned ability to easily halt/clear sandbox apps as well as pause/restart them where we need state, things become complicated with shell scripts, etc. 

I was therefore wondering if we should use Terraform to define all our deployment configuration, essentially making it the only common prerequisite regardless where the sandbox should be deployed. 

If we decide to go this route, we need to decide on whether we still want the setup.env file (I kinda like it as it makes it easy to reuse API/APP keys for multiple apps) or the setup.sh.

**Comment by danielcbright** [comment]
@chrisluekermann go ahead and setup a meeting with myself and anyone else who may be interested in this

**Comment by danielcbright** [comment]
**8/4/21 Discussion:**

- need to find the right balance with how to setup things with Terraform
- how should we split up the Terraform? 
    - write an abstraction? - **YES module**
    - write 4 separate bits of Terraform code, one for each environment? - **YES pick one to start with, and then build from there**
