### ISSUE TITLE
can we add tutorial type resources (how to instrument a go app) to the DPN repo?

### ISSUE THREAD

**Issue by estib** [DataDog/dpn#39]
possible ideas:
- add a readme to already existing sample-apps that walks through and shows how they were instrumented
- add new apps that exist less for demo purposes and more for training purposes
- add redirects to the interactive courses that the learning center offers already

**Comment by estib** [comment]
added Chris to get his perspective on this :) this came up in conversation on the last DPN+ connect

**Comment by chrisluekermann** [comment]
While I like the idea of having such resources for training purposes, I would prefer it if they were not "standalone" applications. Instead, I would like to see us having one cohesive application that can be started instrumented or non-instrumented. 
Our long term goal is to build various enablement sessions around the new sandbox application that help our partners learn and experiment with Datadog but always within the same application. 

So what I'm saying is: Yes, we can do that but that go app should be a microservice that is being used by our sandbox application.
