### ISSUE TITLE
new sample app from microservices-demo: https://github.com/microservices-demo/microservices-demo

### ISSUE THREAD

**Issue by estib** [DataDog/dpn#40]
What doing this would involve:
- look to ecommerce-webapp as a starting point
- [this is the part of the setup.sh that would likely need changing](https://github.com/DataDog/dpn/blob/master/sandbox-apps/ecommerce-webapp/setup.sh#L40-L48)
- most of the actual changes / work would be in [configuring the docker-compose.yml](https://github.com/DataDog/dpn/blob/master/sandbox-apps/ecommerce-webapp/data/docker-compose.yml)

**Comment by ckelner** [comment]
We've got some expertise over in https://github.com/DataDog/bitsboutique on this a bit. We're using it for USM. @ktmq is our expert. Come chat in #demo-environments-backroom if you like,.
